# Generated by Django 2.0.5 on 2020-08-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Full_image_video_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_field_type', models.CharField(max_length=110)),
                ('Image', models.FileField(upload_to='image/')),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Discription', models.CharField(max_length=500)),
                ('Image', models.FileField(upload_to='image/')),
                ('Category', models.CharField(max_length=100)),
                ('News_Date', models.DateTimeField(auto_now_add=True)),
                ('news_resource', models.CharField(max_length=120)),
                ('Upload_view', models.CharField(max_length=110, null=True)),
            ],
        ),
    ]
